#!/bin/bash
doc="TEXT COUNT TABS PER LINE\nJames B. Pease"
usage="TextCountTabsPerLine FILE"
while getopts ':h:' option; do

    case "$option" in
    h) echo -e  $doc'\n\nusage: '$usage
       exit
       ;;
    :) printf "missing argument for -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
    esac
done
awk -F'\t' '{ print NF-1 }' < $1 | sort | uniq -c
