#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8

"""
TREE REROOT BY OUTGROUP
James B. Pease
"""

import sys
from Bio import Phylo
from io import StringIO
from pylib.mixcore import _LICENSE

def generate_argparser():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawTextHelpFormatter,
        epilog=_LICENSE)
    parser.add_argument('tree', type=os.path.abspath,
                        help="tree file (one per line, Newick format)")
    parser.add_argument('outgroup', type=os.path.abspath,
                        help="outgroup name (exact match, case-sensitive)")
    parser.add_argument('--out', type=argparse.FileType('w'),
                        default=sys.stdout, help="output fasta file")
    return parser

def main(arguments=None):
    arguments = arguments if arguments is not None else sys.argv[1:]
    parser = generate_argparser()
    args = parser.parse_args(args=arguments)
    trees = Phylo.parse(args.tree, 'newick')
    for tree in trees:
        tree.root_with_outgroup(args.outgroup)
        print(tree.__format__('newick'), file=args.out)

if __name__ == "__main__":
    main()
